### ISSUE TITLE
Page Not Found 404 error

### ISSUE THREAD

**Issue by alexsoble** [datamade/school-report-cards#5]
Hi all, 

I bumped in to the following error trying to run `make csv`:

```
wget http://www.isbe.net/research/zip/rc97u.zip
--2017-02-19 15:03:17--  http://www.isbe.net/research/zip/rc97u.zip
Resolving www.isbe.net... 206.166.105.79
Connecting to www.isbe.net|206.166.105.79|:80... connected.
HTTP request sent, awaiting response... 302 Redirect
Location: https://www.isbe.net/research/zip/rc97u.zip [following]
--2017-02-19 15:03:18--  https://www.isbe.net/research/zip/rc97u.zip
Connecting to www.isbe.net|206.166.105.79|:443... connected.
HTTP request sent, awaiting response... 404 NOT FOUND
2017-02-19 15:03:19 ERROR 404: NOT FOUND.

make: *** [rc97u.zip] Error 8
```

It looks like the ISBE site structure changed recently: 

https://www.isbe.net/research:

![screen shot 2017-02-19 at 3 07 14 pm](https://cloud.githubusercontent.com/assets/3209501/23106576/1e8c55b6-f6b5-11e6-83ec-39e800ec4b5b.png)

**Comment by JMOCHicago** [comment]
Maybe here now?

https://www.isbe.net/Pages/Data-Analysis.aspx

**Comment by jeancochrane** [comment]
Great catch @alexsoble! I can take a deeper look tomorrow afternoon, but from a preliminary glance @JMOCHicago seems to be on the right track – specifically, [this page](https://www.isbe.net/Pages/Illinois-State-Report-Card-Data.aspx) seems likely to be the new source for the report card ZIP files.

Following the links, the URL that failed in your error message (for `rc97u.zip`) seems to look like this now:

[https://www.isbe.net/_layouts/Download.aspx?SourceUrl=/Documents/rc97u.zip](https://www.isbe.net/_layouts/Download.aspx?SourceUrl=/Documents/rc97u.zip)

I can't verify that the query pattern above will work for every URL in the Makefile, however. It'll probably take some elbow grease to re-source everything.

If you manage to get it sorted out before I do, a pull request would be very welcome!

**Comment by alexsoble** [comment]
Cool! Thanks @jeancochrane and @JMOCHicago! 

@jeancochrane -- have never played with Makefiles before so this could be a fun chance to do that!

**Comment by thcrock** [comment]
I'm playing around with this now. It seems like the new file layout is more standard, in that some files that prior used ftp are now on that Download.aspx link. So the makefile might end up simplified a bit. I'll push up a fork soon.

**Comment by fgregg** [comment]
This has been fixed on master.

**Comment by alexsoble** [comment]
Thanks!!!
